### ISSUE TITLE
subscribers showing up as null

### ISSUE THREAD

**Issue by ghost** [DxsSucuk/YouTubeWrapper#1]
when i do ChannelResult#getSubscriber or ChannelResult#getSubscriberCountText, they both show up as null or 0 even tho the user has subscribers

this is the code im doing if it matters:
```java
    public static void addId(String id) throws IOException, InterruptedException, IllegalAccessException {
        var channel = YouTubeWrapper.getChannel(id);
        System.out.println(channel.getSubscriber());
        System.out.println(channel.getChannelUrl());
        System.out.println(channel.getAvatarUrl());
        System.out.println(channel.getId());
        System.out.println(channel.getDescription());
        System.out.println(channel.getRssUrl());
        System.out.println(channel.getSubscriberCountText());
        System.out.println(channel.getTitle());
        System.out.println(channel.getVanityUrl());
    }

**Comment by DxsSucuk** [comment]
Thanks for reporting this Issue, I will be looking into it! Could you perhaps share the ID with me so I can recreate it?

**Comment by ghost** [comment]
> Thanks for reporting this Issue, I will be looking into it! Could you perhaps share the ID with me so I can recreate it?

the id i was using was this one: UCxQuQaF9TW8f8QEFe66B32g

**Comment by DxsSucuk** [comment]
Has been fixed in the latest commit.

**Comment by ghost** [comment]
thank you
